#theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
# remote_theme: pages-themes/modernist@v0.2.0
title: Efrem Blázquez - Apunts
description: Materials docents per a cicles formatius d'Informàtica
show_downloads: false

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
